### ISSUE TITLE
Could you translate the comments into English?

### ISSUE THREAD

**Issue by daruma3940** [rlcode/reinforcement-learning#21]
Excuse me.
I can not read Korean.
Could you translate the comments into English?

**Comment by manugarri** [comment]
:+1 to this. No docs + comments in english makes this repo useless unfortunately.

**Comment by dnddnjs** [comment]
We are now translating the comments! If you want, We will add docs about the codes

**Comment by manugarri** [comment]
thank you Sir.

**Comment by daruma3940** [comment]
thank you!
