### ISSUE TITLE
sampling from deque

### ISSUE THREAD

**Issue by slakkur1** [rlcode/reinforcement-learning#29]
Great stuff! This has been extremely helpful! My only suggestion would be in line 78, changing _mini_batch = random.sample(self.memory, batch_size)_ to _mini_batch = random.sample(**list**(self.memory), batch_size)_, otherwise you get the following error, _"TypeError: Population must be a sequence or set.  For dicts, use list(d)."_

**Comment by keon** [comment]
@slakkur1
Thanks for your feedback! Which code are you referring to?
It has been working fine on my computer 😉 . Do you have a sample code to recreate the error?
