### ISSUE TITLE
Env BreakoutDeterministic-v4 not found

### ISSUE THREAD

**Issue by ShaniGam** [rlcode/reinforcement-learning#31]
When I try to run Breakout_DQN I get the following error:
`gym.error.DeprecatedEnv: Env BreakoutDeterministic-v4 not found (valid versions include ['BreakoutDeterministic-v3', 'BreakoutDeterministic-v0'])`

What version of gym are you using? (I'm using 0.8.1)

**Comment by zzing0907** [comment]
We use 0.9.1 version of gym. 

If you want to use BreakoutDeterministic-v3
then you should change this part
```
  # change action to real_action
  if action == 0: real_action = 1
  elif action == 1: real_action = 2
  else: real_action = 3
```

like this.
```
  # change action to real_action  
  if action == 0: real_action = 1  
  elif action == 1: real_action = 4  
  else: real_action = 5
```
Maybe it will work. or you can update your gym. 
Thanks.

**Comment by ShaniGam** [comment]
It works now after I updated gym, but now when I try to load the trained model it says:
`ValueError: Dimension 1 in both shapes must be equal, but are 3 and 6 for 'Assign_42' (op: 'Assign') with input shapes: [512,3], [512,6].`

**Comment by keon** [comment]
@ShaniGam I believe our current model and saved model does not match. We are in process of retraining. Should be fixed in a few days. Thanks for your feedback!
