### ISSUE TITLE
Reference links for each algorithm

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#41]
Hi,

It's a really great repo for learning RL. However, if you could provide some links/blogs containing explanation of each algorithm, that will be even more beneficial for users. 

Thanks,
Akilesh

**Comment by dnddnjs** [comment]
Hi @akileshbadrinaaraayanan 
Our purpose is just like what you said. Now we are almost done writing a book about these codes in Korean. We are seriously considering about publishing English about fundamental of RL and explanation about these codes. 

Thank you!
