### ISSUE TITLE
Moving obstacles in Grid World

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#47]
I don't understand the effect of moving obstacles in grid world (Deep SARSA and REINFORCE) as in environment.py, the negative rewards are hard-coded for obstacles at coordinates [0, 1], [1, 2], [2, 3]. 

Thanks,
Akilesh

**Comment by Hyeokreal** [comment]
Hi, Akilesh. I'm sorry for my late reply. 

It seems like hard-coded but not exactly.
The meaning of [0,1], [1,2], [2,3] is just the start point of the obstacles. 
So, as it moves, rewards depend on the changed coordinates.

If you look at the code in this section, you will understand.
(1-grid-world/4-sarsa/environment.py  -- 125~130 lines)
```
        if next_state == self.canvas.coords(self.circle):
            reward = 100
            done = True
        elif next_state in [self.canvas.coords(self.triangle1),
                            self.canvas.coords(self.triangle2)]:
            reward = -100
```

Thank you for your interest,
Hyeokreal.

**Comment by akileshbadrinaaraayanan** [comment]
Thanks Hyeokreal.
