### ISSUE TITLE
Batch size in A2C Cartpole

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#49]
Are there no variants of A2C with mini-batch update instead of training every time step? If yes, could you tell the pros and cons of such an approach?

Thanks,
Akilesh

**Comment by dnddnjs** [comment]
If you want, you can change it from one-step bootstrap to multi-step bootstrap. As I know, one-step bootstrap has lower variance and higher bias than multi-step bootstrap.
