### ISSUE TITLE
Number of actions in deep SARSA grid world

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#51]
Why does the implementation (deep_sarsa_agent.py) have action_space = [0, 1, 2, 3, 4] when there are only 4 possible actions that the agent can take (as specified in the environment.py)?

Thanks,
Akilesh

**Comment by Hyeokreal** [comment]
Hi, Akilesh.

up, down, left, right, stay(don't move) 5 possible actions are exist.

Thanks,
Hyeokreal

**Comment by akileshbadrinaaraayanan** [comment]
Thanks Hyeokreal.
