### ISSUE TITLE
Convergence

### ISSUE THREAD

**Issue by ShaniGam** [rlcode/reinforcement-learning#52]
How many days/episodes did it take until it converged in breakout_a3c? Did you try using LSTM for faster convergence?

**Comment by dnddnjs** [comment]
It took 26 hours to train breakout a3c agent. We have not tried using LSTM on breakout a3c.

**Comment by ShaniGam** [comment]
Really? How many episodes did it take? I've been running it on a very powerful server with a very good gpu and 8 threads for a few days and it has not converged yet.

**Comment by keon** [comment]
A3C breakout took me 8 hours on 7700 CPU & GTX1070 to converge. I used 4 threads.

**Comment by ShaniGam** [comment]
Yes, it's up to date. Is it possible that with 4 thread you get better results than with 8?

**Comment by dnddnjs** [comment]
@ShaniGam
It is better to use more threads when training A3C agent. 8hours is result of good hardware
