### ISSUE TITLE
What each state signifies in Grid World 

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#53]
I understand that state_size is 15. Could you please elaborate on what each of the 15 values denote or signify? 

Thanks,
Akilesh

**Comment by Hyeokreal** [comment]
Hi, Akilsesh. 

1) Relative position of arrival point (x, y)
2) Label of destination
3) Relative position of the obstacle to the agent (x, y)
4) Labels of obstacles
5) Speed of Obstacle

3),4),5) for each obstacle. so the sum of them is 12. 
1) for 2 and 2) for 1. 

Total sum of state_size is 12+2+1 = 15. 

Thanks,
Akilesh.

**Comment by akileshbadrinaaraayanan** [comment]
Hi Hyeokreal,

Thanks for your response. I specifically need help in understanding this portion of the code in get_state() function of environment.py

`for reward in self.rewards:
      reward_location = reward['state']
      states.append(reward_location[0] - agent_x)
      states.append(reward_location[1] - agent_y)`

Could you please explain what's it trying to do?

Thanks,
Akilesh

**Comment by akileshbadrinaaraayanan** [comment]
Thanks Hyeokreal.
