### ISSUE TITLE
Saved model usage

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#57]
Could you please provide examples on how to use the saved model (.h5 files) at test time for Grid world, Cartpole environments?

Thanks,
Akilesh

**Comment by codetiger** [comment]
Just wondering if you saw the functions "agent.model.save_weights" and "agent.model.load_weights" in CartPole DDQN implementation code.
https://github.com/rlcode/reinforcement-learning/blob/master/2-cartpole/2-double-dqn/cartpole_ddqn.py

**Comment by dnddnjs** [comment]
You can use saved model by changing self.load_model from False to True. Take care about the name of saved model. Thanks

**Comment by akileshbadrinaaraayanan** [comment]
Thanks @codetiger  and @dnddnjs

**Comment by Sat0ri** [comment]
Hello, trained agent play CartPole-v1 with score 500, but when I restart it with ..
**self.load_model from = True**
and with correct name, it start learning with low score results.

How can I load weights and start **trained** agent to play, without learning?
