### ISSUE TITLE
Thank you for good materials!

### ISSUE THREAD

**Issue by Hayoung-Kim** [rlcode/reinforcement-learning#59]
https://www.gitbook.com/book/dnddnjs/rl/details에서 RL을 공부하다가 이 깃헙까지 오게되었습니다.

RL관련해서 자료가 없어서 막막한 부분이 있었는데 gitbook에 번역본을 제공해주셔서 빠르게 공부할 수 있었습니다. 감사합니다.

**Comment by dnddnjs** [comment]
감사합니다 저희 다른 레포지토리에 보면 한글로 주석 단 코드들도 있습니다. 이번 달 말에 강화학습 책도 출간합니다. 더 많은 분들의 시간을 단축시킬 수 있으면 좋을 것 같습니다.

**Comment by wooridle** [comment]
반갑습니다!

**Comment by keon** [comment]
봐주셔서 감사할따름입니다 ㅋㅋ.
(그럼 이만 이슈는 닫겠습니다)
