### ISSUE TITLE
Giving image as input in Gridworld

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [rlcode/reinforcement-learning#64]
Hi,

Is it possible to give image as input in Gridworld environment. Can you suggest ways in which this can be done? Are there ways of converting tkinter Canvas into a numpy array which can then be fed into a ConvNet?

Thanks,
Akilesh

**Comment by zzing0907** [comment]
Hi!!
You can use ImageGrab function in PIL. I know only this way to capture image from tkinter canvas.

These links are helpful.
Get image from canvas -> [https://stackoverflow.com/questions/41940945/saving-canvas-from-tkinter-to-file](https://stackoverflow.com/questions/41940945/saving-canvas-from-tkinter-to-file)
Capture size doesn't fit -> [https://stackoverflow.com/questions/24370228/python-imaging-library-fails-to-grab-whole-screen](https://stackoverflow.com/questions/24370228/python-imaging-library-fails-to-grab-whole-screen)
