### ISSUE TITLE
Training time of breakout-dqn

### ISSUE THREAD

**Issue by yhcao6** [rlcode/reinforcement-learning#65]
Can ask how long it takes to train the breakout dqn model, what is your graph card? Thanks !

**Comment by zzing0907** [comment]
I'm sorry for late reply.
We tested dqn model with i5-4690(CPU), gtx1060(GPU) and it took about 40hours.
Score reached about 120 average reward, 300 max reward.

Thanks !!

**Comment by yhcao6** [comment]
Thank you!

2017-10-04 14:58 GMT+08:00 youngmoo <notifications@github.com>:
